[package]
name = "rocket_test_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc.1"
anyhow = "1.0"
sqlx = { version = "0.5.9", features = ["sqlite","runtime-actix-rustls"]}
